# Generated by Django 6.0.1 on 2026-03-25 21:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_billing_type_project_contract_value_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Expected cost to deliver this project', max_digits=15, verbose_name='Estimated cost'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to this project', related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
