# Generated by Django 5.0.6 on 2026-05-12 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_fix_ap_bill_paid_amounts'),
        ('projects', '0006_project_gatepass'),
        ('purchase', '0017_vendor_bill_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_project_expenses', to='purchase.vendorbill'),
        ),
        migrations.AddConstraint(
            model_name='projectexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('vendor_bill__isnull', False)), fields=('vendor_bill',), name='uniq_project_expense_per_vendor_bill'),
        ),
    ]
