# Generated by Django 5.1.4 on 2026-05-16 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_public_upload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technicians',
            field=models.ManyToManyField(blank=True, help_text='Field technicians; clock in to this project on the public attendance link to allocate hours here.', related_name='technician_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
