# Generated by Django 5.0.6 on 2026-05-16 09:11

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storage_location_and_item_enhancements'),
        ('projects', '0009_project_technicians_and_attendance_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItemLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('group_name', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('line_net', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Line amount excluding VAT (matches estimate line total)', max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_item_lines', to='inventory.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_lines', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project item line',
                'verbose_name_plural': 'Project item lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
