# Generated by Django 5.0.6 on 2026-05-19 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_project_item_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='edit_approval_status',
            field=models.CharField(choices=[('none', 'No pending edit review'), ('pending', 'Pending edit approval'), ('rejected', 'Edit rejected')], default='none', help_text='When approval is configured for projects, edits from non-approvers queue here.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_edit_approval_submissions', to=settings.AUTH_USER_MODEL),
        ),
    ]
