# Generated by Django 5.1.4 on 2026-05-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_serial_model_tracking'),
        ('projects', '0012_remove_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectItemDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivered_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_item_deliveries', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_item_deliveries', to='inventory.item')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deliveries', to='projects.project')),
            ],
            options={
                'verbose_name': 'Project item delivery',
                'verbose_name_plural': 'Project item deliveries',
                'ordering': ['-delivered_date', '-pk'],
            },
        ),
    ]
