# Generated by Django 5.1.4 on 2026-05-25 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_project_item_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='operation_manager',
            field=models.ForeignKey(blank=True, help_text='Operation manager for this project. Falls back to Manager when empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_manager_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='site_engineer',
            field=models.ForeignKey(blank=True, help_text='Site engineer responsible for this project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_engineer_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='edit_approval_status',
            field=models.CharField(choices=[('none', 'No pending edit review'), ('pending', 'Pending edit approval'), ('rejected', 'Edit rejected')], default='none', help_text='Pending completion approval when a user requests status Completed.', max_length=20),
        ),
    ]
