# Generated by Django 5.1.4 on 2026-05-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_site_engineer_operation_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='operation_manager',
        ),
        migrations.RemoveField(
            model_name='project',
            name='site_engineer',
        ),
    ]
