# Generated by Django 5.1.4 on 2026-05-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_task_customer_optional_project'),
        ('projects', '0016_remove_site_engineer_operation_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='CRM record when the task is not tied to a project.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.customer', verbose_name='Customer / lead'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project'),
        ),
    ]
