# Generated by Django 5.1.4 on 2026-06-04 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_task_customer_optional_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='conversion_approval_status',
            field=models.CharField(choices=[('none', 'No pending conversion approval'), ('pending', 'Pending conversion approval'), ('rejected', 'Conversion rejected')], default='none', help_text='When set from estimate conversion, project stays in Draft until approved.', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='conversion_approval_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='conversion_approval_submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_conversion_approval_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20),
        ),
    ]
