# Generated by Django 5.0.6 on 2026-06-28 10:40

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_project_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='From estimate conversion: sum of qty × base price per line.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='checklist_public_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='From estimate conversion: net subtotal excluding VAT.', max_digits=15, verbose_name='Estimated cost'),
        ),
    ]
