# Generated by Django 5.1.4 on 2026-07-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentrequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Set automatically when approved via Settings → Approval Configuration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitment_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recruitmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('open', 'Open'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
