# Generated by Django 5.0.6 on 2026-06-28 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0004_contract_terms_and_defaults'),
        ('hr', '0040_alter_employee_options_and_more'),
        ('projects', '0022_alter_project_budget_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_schedule_token', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Operations settings',
                'verbose_name_plural': 'Operations settings',
            },
        ),
        migrations.CreateModel(
            name='StaffDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('duty_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('link_type', models.CharField(choices=[('project', 'Project'), ('amc', 'AMC')], default='project', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('amc_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_duty_schedules', to='contracts.contract', verbose_name='AMC contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='hr.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_duty_schedules', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff duty schedule',
                'verbose_name_plural': 'Staff duty schedules',
                'ordering': ['-duty_date', 'start_time', 'employee__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='staffdutyschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status', 'scheduled')), fields=('employee', 'duty_date'), name='operations_unique_scheduled_duty_per_day'),
        ),
    ]
