# Generated by Django 5.0.6 on 2026-06-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdutyschedule',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact person'),
        ),
        migrations.AddField(
            model_name='staffdutyschedule',
            name='contact_person_phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Contact phone'),
        ),
        migrations.AddField(
            model_name='staffdutyschedule',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
