# Generated by Django 5.1.4 on 2026-07-04 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_contract_estimate_project_links'),
        ('hr', '0044_employee_photo'),
        ('operations', '0002_staffdutyschedule_contact_person_name_and_more'),
        ('projects', '0023_inspection_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffdutyschedule',
            name='operations_unique_scheduled_duty_per_day',
        ),
        migrations.AlterField(
            model_name='staffdutyschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('pending', 'Pending'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='staffdutyschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('status__in', ('scheduled', 'pending', 'in_progress'))), fields=('employee', 'duty_date'), name='operations_unique_scheduled_duty_per_day'),
        ),
    ]
