# Generated by Django 5.1.4 on 2026-07-04 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_planned_visits_and_draft_duties'),
        ('hr', '0044_employee_photo'),
        ('operations', '0003_staff_duty_status_choices'),
        ('projects', '0023_inspection_checklist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='staffdutyschedule',
            name='operations_unique_scheduled_duty_per_day',
        ),
        migrations.AlterField(
            model_name='staffdutyschedule',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Leave empty for AMC auto-drafts until a technician is assigned.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='duty_schedules', to='hr.employee'),
        ),
        migrations.AddConstraint(
            model_name='staffdutyschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('employee__isnull', False), ('is_active', True), ('status__in', ('scheduled', 'pending', 'in_progress'))), fields=('employee', 'duty_date'), name='operations_unique_scheduled_duty_per_day'),
        ),
    ]
