# Generated by Django 6.0.1 on 2026-02-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_add_item_condition_and_condition_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment_reason',
            field=models.CharField(blank=True, choices=[('shrinkage', 'Shrinkage / Count Variance'), ('damage', 'Damage / Write-Off'), ('supplier_return', 'Supplier Return'), ('correction', 'Internal Correction'), ('revaluation', 'Revaluation'), ('other', 'Other')], default='', help_text='Required for adjustments — determines which GL account is hit', max_length=20),
        ),
    ]
