# Generated by Django 6.0.1 on 2026-03-12 11:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def migrate_legacy_items(apps, schema_editor):
    """Copy existing item/quantity to ConsumableRequestItem for backward compatibility."""
    ConsumableRequest = apps.get_model('inventory', 'ConsumableRequest')
    ConsumableRequestItem = apps.get_model('inventory', 'ConsumableRequestItem')
    for cr in ConsumableRequest.objects.filter(item__isnull=False, quantity__isnull=False):
        if not ConsumableRequestItem.objects.filter(consumable_request=cr).exists():
            ConsumableRequestItem.objects.create(
                consumable_request=cr,
                item=cr.item,
                quantity=cr.quantity,
                unit_cost=cr.unit_cost or Decimal('0'),
                total_cost=cr.total_cost or Decimal('0'),
            )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_payroll_accounting'),
        ('inventory', '0007_add_adjustment_reason_to_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consumablerequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests', to='hr.department'),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='required_by_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consumablerequest',
            name='item',
            field=models.ForeignKey(blank=True, limit_choices_to={'item_type': 'product', 'status': 'active'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_requests', to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='consumablerequest',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ConsumableRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='consumable_request_attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('consumable_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='inventory.consumablerequest')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumableRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('consumable_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.consumablerequest')),
                ('item', models.ForeignKey(limit_choices_to={'item_type': 'product', 'status': 'active'}, on_delete=django.db.models.deletion.PROTECT, related_name='consumable_request_items', to='inventory.item')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(migrate_legacy_items, migrations.RunPython.noop),
    ]
