# Generated by Django 5.1.4 on 2026-05-22 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_consumable_request_project'),
        ('projects', '0012_remove_timesheet'),
        ('purchase', '0019_po_goods_receiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='track_by_serial',
            field=models.BooleanField(default=False, help_text='When enabled, stock is tracked by individual model numbers received via PO.'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ItemSerialNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('model_number', models.CharField(max_length=120)),
                ('date_received', models.DateField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('delivered', 'Delivered')], default='available', max_length=20)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('assigned_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_serial_numbers', to='projects.project')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('delivered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_item_serials', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='inventory.item')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serial_numbers', to='purchase.purchaseorderreceiptline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_serial_numbers', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Item serial number',
                'verbose_name_plural': 'Item serial numbers',
                'ordering': ['date_received', 'pk'],
                'indexes': [models.Index(fields=['item', 'status', 'date_received'], name='inventory_i_item_id_446db5_idx'), models.Index(fields=['assigned_project', 'status'], name='inventory_i_assigne_4b4a4f_idx')],
                'constraints': [models.UniqueConstraint(fields=('item', 'model_number'), name='inventory_itemserialnumber_item_model_unique')],
            },
        ),
    ]
