# Generated by Django 5.1.4 on 2026-06-02 12:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_itemgroupmembership'),
        ('settings_app', '0021_company_estimate_default_signatures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='request_kind',
            field=models.CharField(choices=[('consumable', 'Consumable'), ('material', 'Material')], default='consumable', max_length=20),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, help_text='Preferred warehouse to issue stock from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requisitions_source', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='consumablerequest',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumablerequestitem',
            name='line_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consumablerequestitem',
            name='qty_approved',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='consumablerequestitem',
            name='qty_issued',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='consumablerequestitem',
            name='storage_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_lines', to='inventory.storagelocation'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='legal_entity',
            field=models.ForeignKey(blank=True, help_text='Legal entity that owns this warehouse.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='settings_app.company'),
        ),
        migrations.AlterField(
            model_name='consumablerequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('pending', 'Pending'), ('approved', 'Approved'), ('partially_issued', 'Partially Issued'), ('issued', 'Issued'), ('dispensed', 'Dispensed'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
