# Generated by Django 5.0 on 2026-06-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_itemgroupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBaseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'Item base group',
                'verbose_name_plural': 'Item base groups',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='base_group',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional parent base group for organizing sub-groups.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sub_groups',
                to='inventory.itembasegroup',
            ),
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={
                'ordering': ['name'],
                'verbose_name': 'Item sub-group',
                'verbose_name_plural': 'Item sub-groups',
            },
        ),
    ]
