# Generated by Django 5.1.4 on 2026-06-02 12:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_fix_ap_bill_paid_amounts'),
        ('inventory', '0018_procurement_inventory_extension'),
        ('settings_app', '0022_procurement_inventory_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterEntityVatTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('intra_emirate', 'Intra-emirate'), ('inter_emirate', 'Inter-emirate'), ('designated_zone', 'Designated Zone'), ('gcc_cross_border', 'GCC Cross-border'), ('out_of_scope', 'Out of Scope')], max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('vat_rate_override', models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use item tax code rate.', max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InterEntityTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('transfer_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pricing_basis', models.CharField(choices=[('cost', 'At Cost'), ('cost_markup', 'Cost + Markup %'), ('agreed', 'Agreed Price')], default='cost', max_length=20)),
                ('markup_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_dest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfers_approved_dest', to=settings.AUTH_USER_MODEL)),
                ('approved_by_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfers_approved_source', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('destination_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_inter_transfers', to='settings_app.company')),
                ('destination_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfer_destination', to='finance.journalentry')),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_inter_transfers', to='inventory.warehouse')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_inter_transfers', to='settings_app.company')),
                ('source_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfer_source', to='finance.journalentry')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_inter_transfers', to='inventory.warehouse')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vat_treatment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='inventory.interentityvattreatment')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterEntityTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('destination_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfer_dest_lines', to='inventory.stockmovement')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inter_transfer_source_lines', to='inventory.stockmovement')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.interentitytransfer')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issued_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_requisition_issues', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_events', to='inventory.consumablerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisition_issues', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-issued_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRequisitionIssueLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.materialrequisitionissue')),
                ('requisition_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_lines', to='inventory.consumablerequestitem')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisition_issue_lines', to='inventory.stockmovement')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
