# Generated by Django 5.1.4 on 2026-06-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_itemgroup_expense_type'),
        ('inventory', '0020_procurement_seed_data'),
    ]

    operations = [
    ]
