# Generated by Django 5.1.4 on 2026-06-09 21:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_merge_20260610_0047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCostLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qty_remaining', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('received_date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.item')),
                ('source_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_layers', to='inventory.stockmovement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_layers', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['received_date', 'id'],
                'indexes': [models.Index(fields=['item', 'warehouse', 'received_date'], name='inventory_i_item_id_754b35_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('forecast_date', models.DateField()),
                ('forecast_30', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('forecast_60', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('forecast_90', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('avg_monthly_consumption', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('confidence', models.CharField(default='medium', max_length=20)),
                ('reasoning', models.TextField(blank=True)),
                ('raw_response', models.TextField(blank=True)),
                ('refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='inventory.item')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-forecast_date', '-refreshed_at'],
                'indexes': [models.Index(fields=['item', '-refreshed_at'], name='inventory_i_item_id_ad5e06_idx')],
            },
        ),
    ]
