# Generated by Django 5.1.4 on 2026-06-22 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_inventory_ai_hub_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inventorycomplianceflag',
            new_name='inventory_i_run_key_236c72_idx',
            old_name='inv_comp_run_check_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorycomplianceflag',
            new_name='inventory_i_is_reso_63de6b_idx',
            old_name='inv_comp_resolved_idx',
        ),
        migrations.AddField(
            model_name='item',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Primary warehouse where this item is stored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='inventorycomplianceflag',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorycomplianceflag',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
