# Generated by Django 6.0.1 on 2026-02-26 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0021_alter_accountmapping_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentryline',
            name='bank_reconciliation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cleared_lines', to='finance.bankreconciliation'),
        ),
        migrations.AddField(
            model_name='journalentryline',
            name='is_bank_reconciled',
            field=models.BooleanField(default=False),
        ),
    ]
