# Generated by Django 6.0.1 on 2026-02-26 15:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_add_bank_reconciliation_to_journal_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatementline',
            name='match_confidence',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Auto-match confidence: 100 = exact single, 70 = multiple candidates', max_digits=5),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('matched', 'Fully Matched'), ('reconciled', 'Reconciled'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.UniqueConstraint(fields=('statement', 'transaction_date', 'description', 'debit', 'credit'), name='unique_statement_line_content'),
        ),
    ]
