# Generated by Django 6.0.1 on 2026-02-27 13:57
# UAE FTA standard: Draft, Filed, Amended, Locked, Reversed

from django.db import migrations, models


def migrate_vat_return_statuses(apps, schema_editor):
    """Migrate old statuses to UAE FTA standard: posted/submitted/accepted → filed."""
    VATReturn = apps.get_model('finance', 'VATReturn')
    VATReturn.objects.filter(status__in=['posted', 'submitted', 'accepted']).update(status='filed')


def reverse_migrate(apps, schema_editor):
    """Reverse: filed → posted (best-effort rollback)."""
    VATReturn = apps.get_model('finance', 'VATReturn')
    VATReturn.objects.filter(status='filed').update(status='posted')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0023_add_statement_match_confidence'),
    ]

    operations = [
        migrations.RunPython(migrate_vat_return_statuses, reverse_migrate),
        migrations.AlterField(
            model_name='vatreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('filed', 'Filed'), ('amended', 'Amended'), ('locked', 'Locked'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
    ]
