# Generated by Django 6.0.1 on 2026-03-25 13:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_vat_website_scope_project'),
        ('inventory', '0008_consumable_request_enhancements'),
        ('projects', '0003_project_billing_type_project_contract_value_and_more'),
        ('sales', '0007_rename_quotation_to_estimate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimateitem',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='estimate',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_estimates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estimate',
            name='authorized_signature',
            field=models.ImageField(blank=True, help_text='Authorized signatory image', null=True, upload_to='estimate_signatures/'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='client_note',
            field=models.TextField(blank=True, help_text='Note for the client (shown on estimate)'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='customer_signature',
            field=models.ImageField(blank=True, help_text='Customer signature image (e.g. scan)', null=True, upload_to='estimate_signatures/'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last calculated discount amount on total', max_digits=15),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percent', 'Percentage'), ('amount', 'Fixed amount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='estimate',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='estimate',
            name='prepared_by',
            field=models.CharField(blank=True, help_text='Name shown on estimate document', max_length=200),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='projects.project'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='scope',
            field=models.JSONField(blank=True, default=list, help_text='Selected scope tags'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='group_name',
            field=models.CharField(blank=True, help_text='Section / group heading', max_length=200),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='profit_type',
            field=models.CharField(choices=[('none', 'None'), ('percent', 'Percent'), ('amount', 'Amount')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='profit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Unit price including profit (used for line totals)', max_digits=15),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (optional)'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, rate includes VAT'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Base unit price (e.g. from inventory)', max_digits=15),
        ),
    ]
