# Generated by Django 6.0.1 on 2026-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_estimate_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='show_rates_on_pdf',
            field=models.BooleanField(default=True, help_text='If off, PDF shows description and quantity only; totals still show VAT and amount.'),
        ),
    ]
