# Generated by Django 5.0.6 on 2026-05-11 12:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_estimate_show_rates_on_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimateitem',
            name='profit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Per unit: % markup on base, or AED added to base (not total for the whole line).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Selling price per unit after profit: Base + profit (AED) or Base × (1 + profit%).', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Base price per unit (before profit).', max_digits=15),
        ),
    ]
