# Generated by Django 5.0.6 on 2026-05-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_estimate_status_quotation_won_lost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('quotation_won', 'Quot Won'), ('quotation_lost', 'Quot Lost')], default='draft', max_length=20),
        ),
    ]
