# Generated by Django 5.1.4 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_approval_estimate_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='revision_count',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Increments when resubmitted for approval after an edit rejection (R1, R2, … on PDF).',
            ),
        ),
    ]
