# Generated by Django 5.1.4 on 2026-05-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_estimate_revision_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='approval_requested_by',
            field=models.ForeignKey(
                blank=True,
                help_text='User who last sent the estimate for status approval (Sent).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='estimate_status_approval_requests',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
