# Generated by Django 5.1.4 on 2026-05-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_estimate_approval_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='awaiting_resubmit_revision',
            field=models.BooleanField(
                default=False,
                help_text='Set when status is rejected; next Mark as Sent bumps revision (R1, R2, …).',
            ),
        ),
    ]
