# Generated by Django 5.1.4 on 2026-05-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_estimate_awaiting_resubmit_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateProformaInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('charge_type', models.CharField(choices=[('percent', 'Percentage of quotation subtotal'), ('amount', 'Fixed amount (excl. VAT)')], max_length=20)),
                ('charge_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('line_subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_proforma_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proforma_invoices', to='sales.estimate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
