# Generated by Django 5.1.4 on 2026-05-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_estimate_show_group_totals_on_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('under_negotiation', 'Under Negotiation'), ('quotation_won', 'Quot Won'), ('quotation_lost', 'Quot Lost')], default='draft', max_length=20),
        ),
    ]
