# Generated by Django 5.1.4 on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_estimate_status_under_negotiation'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='scope_of_work',
            field=models.CharField(
                blank=True,
                choices=[
                    ('two_way_manifold', '2 Way Manifold System'),
                    ('four_way_manifold', '4 Way Manifold System'),
                    ('central_tank', 'Central Tank System'),
                    ('rectification', 'Rectification Work'),
                    ('fitout', 'Fitout'),
                ],
                default='',
                max_length=40,
                verbose_name='Scope of work',
            ),
        ),
        migrations.AddField(
            model_name='estimate',
            name='type_of_occupancy',
            field=models.CharField(
                blank=True,
                choices=[
                    ('residential', 'Residential'),
                    ('commercial', 'Commercial'),
                    ('labour_accommodation', 'Labour Accommodation'),
                    ('restaurants', 'Restaurants'),
                    ('factories_industries', 'Factories - Industries'),
                ],
                default='',
                max_length=40,
                verbose_name='Type of occupancy',
            ),
        ),
        migrations.AddField(
            model_name='estimate',
            name='type_of_work',
            field=models.CharField(
                blank=True,
                choices=[
                    ('installation_with_amc', 'Installation with AMC'),
                    ('installation_without_amc', 'Installation without AMC'),
                    ('amc', 'AMC'),
                    ('maintenance', 'Maintenance'),
                    ('direct_sale', 'Direct Sale'),
                ],
                default='',
                max_length=40,
                verbose_name='Type of work',
            ),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='scope',
            field=models.JSONField(blank=True, default=list, help_text='Legacy scope tags (deprecated)'),
        ),
    ]
