# Generated by Django 5.0.6 on 2026-06-01 21:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_estimateitem_group_qty_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='discount_applied',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Last calculated discount amount on subtotal (excl. VAT)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='show_group_totals_on_pdf',
            field=models.BooleanField(default=False, help_text='If on, PDF shows each group heading and a subtotal after its line items.'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='type_of_occupancy',
            field=models.CharField(blank=True, choices=[('residential', 'Residential'), ('villa', 'Villa'), ('commercial', 'Commercial'), ('labour_accommodation', 'Labour Accommodation'), ('restaurants', 'Restaurants'), ('factories_industries', 'Factories/Industries')], default='', max_length=40, verbose_name='Type of occupancy'),
        ),
    ]
