# Generated by Django 4.2.11 on 2026-06-03 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_estimate_occupancy_villa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='scope_of_work',
            field=models.CharField(blank=True, default='', help_text='Inventory base group name (main group).', max_length=200, verbose_name='Scope of work'),
        ),
    ]
