# Generated by Django 4.2.11 on 2026-06-03 10:43

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0025_estimate_scope_of_work_base_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateRevisionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField(default=0, help_text='revision_count at snapshot time (0 = original before R1).')),
                ('revision_label', models.CharField(blank=True, help_text='Empty for original; R1, R2, … for revisions.', max_length=10)),
                ('status_at_snapshot', models.CharField(blank=True, max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('snapshot_data', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='estimate_revisions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_revision_snapshots_created', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_snapshots', to='sales.estimate')),
            ],
            options={
                'verbose_name': 'Estimate revision snapshot',
                'verbose_name_plural': 'Estimate revision snapshots',
                'ordering': ['revision_number', 'created_at'],
            },
        ),
    ]
