# Generated by Django 6.0.1 on 2026-02-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_add_tax_code_to_line_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='goods_received',
            field=models.BooleanField(default=False, help_text='If True, this bill is for goods already received into inventory. Posting will debit GRN Clearing (2010) instead of Expense to close the 3-way match: PO → GRN → Bill.'),
        ),
    ]
