# Generated by Django 6.0.1 on 2026-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_add_pr_rejection_reason_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
    ]
