# Generated by Django 6.0.1 on 2026-04-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storage_location_and_item_enhancements'),
        ('purchase', '0013_add_pr_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request_lines', to='inventory.item'),
        ),
    ]
