# Generated by Django 6.0.1 on 2026-04-13 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_storage_location_and_item_enhancements'),
        ('purchase', '0014_purchaserequestitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_lines', to='inventory.item'),
        ),
    ]
