# Generated by Django 6.0.1 on 2026-04-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_purchaseorderitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestattachment',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Quoted total from vendor (optional, free text workflow)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequestattachment',
            name='vendor',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
