# Generated by Django 5.0.6 on 2026-05-12 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0016_purchaserequestattachment_vendor_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorBillAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vendor_bill_attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, help_text='Original filename for display', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.vendorbill')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
