# Generated by Django 5.0.6 on 2026-05-12 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectexpense_vendor_bill_and_more'),
        ('purchase', '0017_vendor_bill_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='project',
            field=models.ForeignKey(blank=True, help_text='If set, bill totals count toward this project after posting (see Projects → Expenses).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='projects.project'),
        ),
    ]
