# Generated by Django 5.1.4 on 2026-06-02 12:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_procurement_models'),
        ('purchase', '0019_po_goods_receiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grn_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('received_on', models.DateField()),
                ('supplier_delivery_note', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_documents', to='purchase.purchaseorder')),
                ('purchase_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_document', to='purchase.purchaseorderreceipt')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_notes_received', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipt_notes', to='purchase.vendor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_documents', to='inventory.warehouse')),
            ],
            options={
                'verbose_name': 'Goods Receipt Note',
                'verbose_name_plural': 'Goods Receipt Notes',
                'ordering': ['-received_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grn_attachments/%Y/%m/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.goodsreceiptnote')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GRNLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('received_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('accepted_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('rejected_qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('qc_status', models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.goodsreceiptnote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_lines', to='inventory.item')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_lines', to='purchase.purchaseorderitem')),
                ('receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_line', to='purchase.purchaseorderreceiptline')),
                ('stock_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_lines', to='inventory.stockmovement')),
                ('storage_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storagelocation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rfq_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('required_by_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('quotes_received', 'Quotes Received'), ('awarded', 'Awarded'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('award_justification', models.CharField(blank=True, choices=[('price', 'Lowest Price'), ('lead_time', 'Shortest Lead Time'), ('quality', 'Quality / Specification'), ('other', 'Other')], max_length=20)),
                ('award_notes', models.TextField(blank=True)),
                ('awarded_at', models.DateTimeField(blank=True, null=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs_awarded', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('material_requisition', models.ForeignKey(blank=True, help_text='Optional MR to pull requested lines from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='inventory.consumablerequest')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=15)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('spec_notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rfq_lines', to='inventory.item')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.rfq')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quote_reference', models.CharField(blank=True, max_length=120)),
                ('validity_date', models.DateField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rfq_quotes/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='purchase.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfq_quotes', to='purchase.vendor')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['supplier__name'],
                'unique_together': {('rfq', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierQuoteLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('available_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('line_lead_time_days', models.PositiveIntegerField(blank=True, null=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchase.supplierquote')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quote_lines', to='purchase.rfqline')),
            ],
            options={
                'ordering': ['rfq_line__sort_order'],
                'unique_together': {('quote', 'rfq_line')},
            },
        ),
        migrations.CreateModel(
            name='RFQAwardLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_qty', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfq_award_lines', to='purchase.purchaseorder')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='purchase.rfq')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchase.vendor')),
                ('rfq_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='purchase.rfqline')),
                ('supplier_quote_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.supplierquoteline')),
            ],
            options={
                'ordering': ['rfq_line__sort_order'],
            },
        ),
    ]
