# Generated by Django 5.0.6 on 2026-06-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0021_vendor_location_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='submission_source',
            field=models.CharField(choices=[('internal', 'Internal'), ('public_link', 'Public link')], default='internal', max_length=20),
        ),
    ]
