# Generated by Django 5.1.4 on 2026-07-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0029_purchaserequestitem_brand_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='model',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
