# Generated by Django 4.2.11 on 2026-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0033_purchaserequestattachment_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('USD', 'USD - US Dollar'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('INR', 'INR - Indian Rupee')], default='AED', max_length=3),
        ),
    ]
