# Generated by Django 5.1.4 on 2026-06-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiModuleKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('purchase_request', 'Purchase request'), ('purchase_order', 'Purchase order'), ('estimate', 'Quotation / estimate'), ('project', 'Project'), ('employee', 'Employee')], max_length=40, unique=True)),
                ('content', models.TextField(blank=True, help_text='Rules, compliance notes, and knowledge graph text for AI reviewers.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI module knowledge',
                'verbose_name_plural': 'AI module knowledge',
                'ordering': ['module'],
            },
        ),
    ]
