# Generated by Django 6.0.1 on 2026-03-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0004_alter_auditlog_action_alter_modulepermission_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='estimate_default_client_note',
            field=models.TextField(blank=True, help_text='Default client note appended to new estimates. Edit in Company Settings.'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='estimate_default_terms',
            field=models.TextField(blank=True, help_text='Default terms & conditions for new estimates. Edit here; each estimate can still be customized.'),
        ),
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('service_request', 'Service Request')], max_length=50, unique=True),
        ),
    ]
