# Generated by Django 6.0.1 on 2026-03-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_estimate_enhancements'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='website',
            field=models.URLField(blank=True, help_text='Company website (shown on PDFs if set)'),
        ),
    ]
