# Generated by Django 6.0.1 on 2026-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_add_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('service_request', 'Service Request'), ('contracts', 'Contracts'), ('settings', 'Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('contracts', 'Contracts'), ('settings', 'Settings')], max_length=50),
        ),
    ]
