# Generated by Django 6.0.1 on 2026-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_contracts_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='contract_default_terms',
            field=models.TextField(blank=True, help_text='Default terms & conditions for new contracts. Edit here; each contract can still be customized.'),
        ),
    ]
