# Generated by Django 6.0.1 on 2026-04-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0009_companysettings_inventory_valuation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='smtp_from_email',
            field=models.EmailField(blank=True, help_text='From address for outbound mail. If empty, Company email is used.', max_length=254),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='smtp_host',
            field=models.CharField(blank=True, help_text='SMTP server (e.g. smtp.office365.com). Leave blank to use server default email settings.', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='SMTP password. Leave blank when saving to keep the existing password.', max_length=200),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='smtp_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
