# Generated by Django 5.0.6 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0011_company_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='Company bank IBAN (WPS SCR).', max_length=34),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_routing_code',
            field=models.CharField(blank=True, help_text='Company bank routing / agent ID (WPS SCR).', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='mol_number',
            field=models.CharField(blank=True, help_text='UAE Ministry of Labour employer registration (WPS SCR).', max_length=20, verbose_name='MOL number'),
        ),
    ]
