# Generated by Django 5.0.6 on 2026-05-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0012_company_wps_fields_uae_compliance_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='estimate_to_project_prompt_include_lines',
            field=models.BooleanField(default=True, help_text='If on: "Convert to project" asks whether to copy all estimate lines as project tasks. If off: conversion creates the project only (no line items copied).'),
        ),
        migrations.AlterField(
            model_name='modulepermission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('service_request', 'Service Request'), ('contracts', 'Contracts'), ('fleet', 'Fleet'), ('settings', 'Settings')], max_length=50),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('contracts', 'Contracts'), ('fleet', 'Fleet'), ('settings', 'Settings')], max_length=50),
        ),
    ]
