# Generated by Django 5.0.6 on 2026-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0013_estimate_to_project_prompt_include_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='estimate_to_project_prompt_include_lines',
            field=models.BooleanField(default=True, help_text='If on: converting an estimate to a project asks whether to copy all estimate lines into the project Items scope table (not Tasks). If off: only the empty project shell is created.'),
        ),
    ]
