# Generated by Django 5.0.6 on 2026-05-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0014_estimate_to_project_help_text_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('service_request', 'Service Request'), ('estimate', 'Sales Estimate'), ('project', 'Project')], max_length=50, unique=True),
        ),
    ]
