# Generated by Django 5.1.4 on 2026-05-25 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0017_site_engineer_operation_manager_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalconfiguration',
            name='manager_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_configs_leave_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('service_request', 'Service Request'), ('estimate', 'Sales Estimate'), ('project', 'Project'), ('leave', 'Leave Request')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('contracts', 'Contracts'), ('fleet', 'Fleet'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50),
        ),
    ]
