# Generated by Django 5.1.4 on 2026-06-02 12:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0028_fix_ap_bill_paid_amounts'),
        ('settings_app', '0021_company_estimate_default_signatures'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='base_currency',
            field=models.CharField(default='AED', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='intercompany_payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities_interco_pay', to='finance.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='intercompany_receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_entities_interco_recv', to='finance.account'),
        ),
        migrations.AddField(
            model_name='company',
            name='trn',
            field=models.CharField(blank=True, max_length=20, verbose_name='Tax Registration Number (TRN)'),
        ),
        migrations.AddField(
            model_name='companysettings',
            name='grn_over_receipt_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Allow receipt up to this % over PO qty (0 = strict).', max_digits=5),
        ),
    ]
