# Generated by Django 5.1.4 on 2026-06-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0022_company_estimate_pdf_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('service_request', 'Service Request'), ('estimate', 'Sales Estimate'), ('project', 'Project'), ('project_conversion', 'Project from estimate (draft)'), ('leave', 'Leave Request')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='estimate_pdf_footer_image',
            field=models.ImageField(blank=True, help_text='Image 2 — shown under company VAT / TRN on estimate quotation PDFs (right).', null=True, upload_to='company/estimate_pdf/'),
        ),
        migrations.AlterField(
            model_name='companysettings',
            name='estimate_pdf_stamp_image',
            field=models.ImageField(blank=True, help_text='Image 1 — shown under company VAT / TRN on estimate quotation PDFs (left).', null=True, upload_to='company/estimate_pdf/'),
        ),
    ]
