# Generated by Django 5.1.4 on 2026-06-09 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0022_procurement_inventory_extension'),
        ('settings_app', '0024_item_subgroup_expense_type'),
    ]

    operations = [
    ]
