# Generated by Django 5.1.4 on 2026-06-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0025_merge_20260610_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Encrypted OpenAI API key for inventory AI forecasting.', max_length=512),
        ),
    ]
