# Generated by Django 5.1.4 on 2026-06-22 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0028_ai_stripe_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicreditpurchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='aicreditpurchase',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
