# Generated by Django 5.1.4 on 2026-06-29 07:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_alter_employee_options_and_more'),
        ('settings_app', '0030_support_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatetexttemplate',
            name='template_type',
            field=models.CharField(choices=[('client_note', 'Payment terms'), ('terms', 'Terms & conditions')], max_length=20),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('crm', 'CRM'), ('sales', 'Sales'), ('purchase', 'Purchase'), ('inventory', 'Inventory'), ('finance', 'Finance'), ('projects', 'Projects'), ('hr', 'HR'), ('documents', 'Documents'), ('assets', 'Fixed Assets'), ('property', 'Property Management'), ('contracts', 'Contracts'), ('support', 'Support'), ('fleet', 'Fleet'), ('reports', 'Reports'), ('settings', 'Settings')], max_length=50),
        ),
        migrations.CreateModel(
            name='ForecastSalesAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('achieved_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual value achieved for the month (AED).', max_digits=15)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_achievements', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Forecast sales achievement',
                'verbose_name_plural': 'Forecast sales achievements',
                'ordering': ['-year', '-month', 'employee__first_name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'year', 'month'), name='settings_unique_forecast_achievement_per_month')],
            },
        ),
    ]
