# Generated by Django 5.1.4 on 2026-06-29 09:05

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_contractdocumentexpiry'),
        ('crm', '0017_crmleadkanbanstage_is_site_visit'),
        ('projects', '0023_inspection_checklist'),
        ('purchase', '0028_purchaserequest_vendor_quote_analysis_running'),
        ('sales', '0035_cashflow_month_sheet'),
        ('settings_app', '0031_forecast_sales_achievement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlowMonthSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('cash_bank_in_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cash/bank balance for summary (AED).', max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash flow month sheet',
                'verbose_name_plural': 'Cash flow month sheets',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowIncomeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('amc', 'AMC'), ('project', 'Project'), ('decor', 'Decor'), ('office', 'Office')], default='project', max_length=30)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('payment_type', models.CharField(choices=[('bank_adcb', 'Bank/ADCB'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('online', 'Online')], default='bank_adcb', max_length=20)),
                ('sales_man', models.CharField(blank=True, max_length=200)),
                ('income_expected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('line_kind', models.CharField(choices=[('normal', 'Normal'), ('unexpected_income', 'Unexpected Income')], default='normal', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('amc_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_income_lines', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_income_lines', to='crm.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_income_lines', to='sales.invoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_income_lines', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_lines', to='settings_app.cashflowmonthsheet')),
            ],
            options={
                'ordering': ['sort_order', 'line_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowExpenseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(choices=[('purchase', 'Purchase'), ('salary', 'Salary'), ('loan', 'Loan'), ('vehicle_loan_emi', 'Vehicle Loan / EMI'), ('visa_exp', 'Visa Exp'), ('office', 'Office'), ('utility', 'Utility'), ('labor', 'Labor'), ('settlement', 'Settlement'), ('civil_defence_fee', 'Civil Defence Fee'), ('reserve_fund', 'Reserve Fund'), ('pdc_cheques', 'PDC Cheques'), ('manpower', 'Manpower')], default='purchase', max_length=30)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('payment_type', models.CharField(choices=[('pdc', 'PDC'), ('cheque', 'Cheque'), ('cash', 'Cash'), ('bank', 'Bank'), ('emi', 'EMI'), ('online', 'Online')], default='bank', max_length=20)),
                ('expense', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('line_kind', models.CharField(choices=[('normal', 'Normal'), ('vehicle_petrol', 'Vehicle Petrol'), ('unexpected_expense', 'Unexpected Expense')], default='normal', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_expense_lines', to='purchase.vendor')),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_expense_lines', to='purchase.vendorbill')),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_lines', to='settings_app.cashflowmonthsheet')),
            ],
            options={
                'ordering': ['sort_order', 'line_date', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CashFlowChequeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('line_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('maintenance', 'Maintenance'), ('amc', 'AMC'), ('project', 'Project'), ('decor', 'Decor'), ('office', 'Office')], default='maintenance', max_length=30)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('income_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cashflow_cheque_lines', to='crm.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_cheque_lines', to='sales.invoice')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_lines', to='settings_app.cashflowmonthsheet')),
            ],
            options={
                'ordering': ['sort_order', 'line_date', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='cashflowmonthsheet',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='settings_unique_cashflow_sheet_per_month'),
        ),
    ]
