# Generated by Django 5.1.4 on 2026-07-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0036_other_service_expenses_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalconfiguration',
            name='module',
            field=models.CharField(choices=[('purchase_request', 'Purchase Request'), ('inventory_request', 'Consumable / Inventory Request'), ('service_request', 'Service Request'), ('estimate', 'Sales Estimate'), ('project', 'Project'), ('project_conversion', 'Project from estimate (draft)'), ('leave', 'Leave Request'), ('recruitment_request', 'Recruitment Request')], max_length=50, unique=True),
        ),
    ]
