# Generated by Django 5.1.4 on 2026-07-14 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0039_module_access_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='moduleaccessrequest',
            name='settings_unique_pending_module_request',
        ),
        migrations.RemoveField(
            model_name='moduleaccessrequest',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='moduleaccessrequest',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='moduleaccessrequest',
            name='reviewed_by',
        ),
        migrations.AlterField(
            model_name='moduleaccessrequest',
            name='status',
            field=models.CharField(choices=[('sent', 'Request sent')], default='sent', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='moduleaccessrequest',
            constraint=models.UniqueConstraint(fields=('user', 'module'), name='settings_unique_module_access_request'),
        ),
    ]
