# Generated by Django 4.2.11 on 2026-07-15 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0044_purchase_role_procurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=50)),
                ('feature', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_permissions', to='settings_app.role')),
            ],
            options={
                'ordering': ['role', 'module', 'feature'],
                'unique_together': {('role', 'module', 'feature')},
            },
        ),
    ]
