"""
Premium-styled PDF (ReportLab) and Excel (openpyxl) exports for consumable inventory reports.
"""
from __future__ import annotations

import html
import io
from datetime import date
from django.conf import settings
from django.http import HttpResponse
from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from apps.settings_app.models import CompanySettings


def _company_context():
    cs = CompanySettings.get_settings()
    logo_path = None
    if cs.logo:
        try:
            logo_path = cs.logo.path
        except Exception:
            logo_path = None
    if not logo_path:
        import os

        static_logo = os.path.join(settings.BASE_DIR, 'static', 'logo.png')
        if os.path.isfile(static_logo):
            logo_path = static_logo
    return {
        'company_name': cs.company_name,
        'address': cs.address or '',
        'currency': cs.currency or 'AED',
        'logo_path': logo_path,
    }


def _cell_text(row: dict, col: dict):
    key = col['key']
    if key not in row:
        return ''
    v = row[key]
    fmt = col.get('format')
    if fmt == 'money':
        return f"{v:,.2f}"
    if fmt == 'number' and isinstance(v, float):
        return f"{v:,.2f}" if v != int(v) else str(int(v))
    return str(v)


def export_report_pdf(report_payload: dict, date_from: date, date_to: date, generated_by: str) -> bytes:
    ctx = _company_context()
    buf = io.BytesIO()
    page_size = landscape(A4)
    doc = SimpleDocTemplate(
        buf,
        pagesize=page_size,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
        topMargin=14 * mm,
        bottomMargin=16 * mm,
        title=report_payload.get('title', 'Report'),
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'RTitle',
        parent=styles['Heading2'],
        alignment=1,
        fontSize=14,
        spaceAfter=6,
        textColor=colors.HexColor('#1e3a5f'),
    )
    meta_style = ParagraphStyle('Meta', parent=styles['Normal'], fontSize=8, alignment=1, textColor=colors.HexColor('#4b5563'))
    header_blue = colors.HexColor('#1e3a5f')
    alt1 = colors.HexColor('#ffffff')
    alt2 = colors.HexColor('#f7f9fc')

    story = []
    # Header row: logo (optional) + company block
    header_data = []
    if ctx['logo_path']:
        from reportlab.platypus import Image as RLImage

        try:
            img = RLImage(ctx['logo_path'], width=28 * mm, height=14 * mm, kind='proportional')
        except Exception:
            img = Paragraph('', styles['Normal'])
    else:
        img = Paragraph('', styles['Normal'])
    addr = html.escape(ctx['address'] or '').replace('\n', '<br/>')
    right_txt = f"<b>{html.escape(ctx['company_name'])}</b><br/>{addr}"
    header_data.append([img, Paragraph(right_txt, ParagraphStyle('co', parent=styles['Normal'], fontSize=9, alignment=2))])
    ht = Table(header_data, colWidths=[40 * mm, doc.width - 40 * mm])
    ht.setStyle(TableStyle([('VALIGN', (0, 0), (-1, -1), 'TOP')]))
    story.append(ht)
    story.append(Spacer(1, 4 * mm))

    period_txt = f"{date_from.isoformat()} to {date_to.isoformat()}"
    story.append(Paragraph(html.escape(report_payload.get('title', 'Report')), title_style))
    story.append(
        Paragraph(
            f"Generated: {date.today().isoformat()} &nbsp;|&nbsp; Period: {period_txt} &nbsp;|&nbsp; Generated by: {generated_by}",
            meta_style,
        )
    )
    story.append(Spacer(1, 2 * mm))
    story.append(Paragraph("<para><font color='#cbd5e1'>________________________________________________________________________</font></para>", styles['Normal']))
    story.append(Spacer(1, 4 * mm))

    if report_payload.get('valuation_method'):
        story.append(Paragraph(f"<b>Valuation method:</b> {report_payload['valuation_method']}", styles['Normal']))
        story.append(Spacer(1, 2 * mm))

    cols = report_payload.get('columns', [])
    rows = report_payload.get('rows', [])
    headers = [c['label'] for c in cols]
    data = [headers]
    status_colors = {
        'danger': colors.HexColor('#fecaca'),
        'warning': colors.HexColor('#fef3c7'),
        'success': colors.HexColor('#dcfce7'),
        'secondary': colors.HexColor('#e5e7eb'),
    }
    status_col_idx = None
    for i, c in enumerate(cols):
        if c['key'] == 'status':
            status_col_idx = i
            break

    for row in rows:
        data.append([_cell_text(row, c) for c in cols])

    if report_payload.get('footer') and 'grand_total_value' in report_payload['footer']:
        foot = report_payload['footer']
        pad = [''] * (len(headers) - 2)
        data.append(pad + ['Grand Total', f"{foot['grand_total_value']:,.2f}"])

    tw = doc.width
    cw = tw / max(len(headers), 1)
    col_widths = [cw] * len(headers)

    t = Table(data, repeatRows=1, colWidths=col_widths)
    ts = [
        ('BACKGROUND', (0, 0), (-1, 0), header_blue),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
        ('TOPPADDING', (0, 0), (-1, 0), 6),
        ('LINEBELOW', (0, 0), (-1, 0), 1, colors.HexColor('#0f172a')),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [alt1, alt2]),
        ('GRID', (0, 0), (-1, -1), 0.25, colors.HexColor('#e5e7eb')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]
    if status_col_idx is not None:
        for ri, r in enumerate(rows, start=1):
            sk = r.get('status_key')
            if sk in status_colors:
                ts.append(('BACKGROUND', (status_col_idx, ri), (status_col_idx, ri), status_colors[sk]))
    if report_payload.get('footer'):
        ts.append(('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold'))
        ts.append(('LINEABOVE', (0, -1), (-1, -1), 1, colors.black))
    t.setStyle(TableStyle(ts))
    story.append(t)

    def _footer(canvas, doc_):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#6b7280'))
        canvas.drawString(12 * mm, 8 * mm, 'Confidential — Internal Use Only')
        page_num = canvas.getPageNumber()
        canvas.drawRightString(page_size[0] - 12 * mm, 8 * mm, f'Page {page_num}')
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    pdf = buf.getvalue()
    buf.close()
    return pdf


def export_report_xlsx(report_payload: dict, date_from: date, date_to: date, generated_by: str) -> bytes:
    ctx = _company_context()
    wb = Workbook()
    ws = wb.active
    ws.title = (report_payload.get('title') or 'Report')[:31]

    brand = '1e3a5f'
    header_fill = PatternFill('solid', fgColor=brand)
    header_font = Font(color='FFFFFF', bold=True, size=11)
    total_font = Font(bold=True)
    thin = Side(style='thin', color='CCCCCC')
    border = Border(left=thin, right=thin, top=thin, bottom=thin)

    ws.merge_cells(start_row=1, start_column=1, end_row=1, end_column=8)
    c1 = ws.cell(row=1, column=1, value=ctx['company_name'])
    c1.font = Font(size=16, bold=True, color=brand)
    c1.alignment = Alignment(horizontal='center')

    ws.merge_cells(start_row=2, start_column=1, end_row=2, end_column=8)
    c2 = ws.cell(row=2, column=1, value=f"{report_payload.get('title', 'Report')} — {date_from} to {date_to}")
    c2.alignment = Alignment(horizontal='center', wrap_text=True)
    c2.font = Font(size=12, bold=True)

    ws.merge_cells(start_row=3, start_column=1, end_row=3, end_column=8)
    meta = f"Generated {date.today().isoformat()} | By {generated_by} | Currency {ctx['currency']}"
    if report_payload.get('valuation_method'):
        meta += f" | Valuation: {report_payload['valuation_method']}"
    ws.cell(row=3, column=1, value=meta).alignment = Alignment(horizontal='center')
    ws.append([])
    start_row = 5

    cols = report_payload.get('columns', [])
    headers = [c['label'] for c in cols]
    for col_idx, h in enumerate(headers, start=1):
        cell = ws.cell(row=start_row, column=col_idx, value=h)
        cell.fill = header_fill
        cell.font = header_font
        cell.border = border
        cell.alignment = Alignment(horizontal='center', vertical='center', wrap_text=True)

    status_key_for_col = None
    for i, c in enumerate(cols):
        if c['key'] == 'status':
            status_key_for_col = i + 1
            break

    r_idx = start_row
    for row in report_payload.get('rows', []):
        r_idx += 1
        for col_idx, c in enumerate(cols, start=1):
            v = _cell_text(row, c)
            cell = ws.cell(row=r_idx, column=col_idx, value=v)
            cell.border = border
            if status_key_for_col == col_idx:
                sk = row.get('status_key')
                if sk == 'danger':
                    cell.fill = PatternFill('solid', fgColor='FFCDD2')
                elif sk == 'warning':
                    cell.fill = PatternFill('solid', fgColor='FFF9C4')
                elif sk == 'success':
                    cell.fill = PatternFill('solid', fgColor='C8E6C9')
                elif sk == 'secondary':
                    cell.fill = PatternFill('solid', fgColor='E0E0E0')

    if report_payload.get('footer') and 'grand_total_value' in report_payload['footer']:
        r_idx += 1
        foot = report_payload['footer']
        for col_idx in range(1, len(headers) - 1):
            ws.cell(row=r_idx, column=col_idx, value='').border = border
        ws.cell(row=r_idx, column=len(headers) - 1, value='Grand Total').font = total_font
        ws.cell(row=r_idx, column=len(headers), value=float(foot['grand_total_value'])).font = total_font

    for i in range(1, len(headers) + 1):
        ws.column_dimensions[get_column_letter(i)].width = min(28, max(12, len(headers[i - 1]) + 4))

    out = io.BytesIO()
    wb.save(out)
    return out.getvalue()
