from django.urls import path
from django.views.generic import RedirectView

from . import views
from . import views_attendance as av
from . import views_extended as vx
from . import views_leave_extended as lvx

app_name = 'hr'

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='hr:dashboard', permanent=False)),
    path('dashboard/', vx.HRDashboardView.as_view(), name='dashboard'),
    path('compliance/', vx.ComplianceDashboardView.as_view(), name='compliance_dashboard'),
    path('settings/payroll/', vx.PayrollSettingsView.as_view(), name='payroll_settings'),
    path('employees/', views.EmployeeListView.as_view(), name='employee_list'),
    path('employees/create/', views.EmployeeCreateView.as_view(), name='employee_create'),
    path('employees/<int:pk>/', views.EmployeeDetailView.as_view(), name='employee_detail'),
    path('employees/<int:pk>/edit/', views.EmployeeUpdateView.as_view(), name='employee_edit'),
    path('departments/', views.DepartmentListView.as_view(), name='department_list'),
    path('leave/types/', lvx.LeaveTypeListView.as_view(), name='leave_type_list'),
    path('leave/types/create/', lvx.LeaveTypeCreateView.as_view(), name='leave_type_create'),
    path('leave/types/<int:pk>/edit/', lvx.LeaveTypeUpdateView.as_view(), name='leave_type_edit'),
    path('leave/types/<int:pk>/deactivate/', lvx.leave_type_deactivate, name='leave_type_deactivate'),
    path('leave/pending/', lvx.LeavePendingHRView.as_view(), name='leave_pending_hr'),
    path('leave/calendar/', lvx.LeaveCalendarView.as_view(), name='leave_calendar'),
    path('leave/apply/', lvx.PublicLeaveApplyView.as_view(), name='public_leave_apply'),
    path('leave/apply/done/', lvx.PublicLeaveApplyDoneView.as_view(), name='public_leave_done'),
    path('leave/api/lookup/', lvx.public_leave_lookup, name='public_leave_lookup'),
    path('leave/api/balance/', lvx.leave_balance_ajax, name='leave_balance_ajax'),
    path('api/employee-leave-context/', lvx.employee_leave_context, name='employee_leave_context'),
    path('api/leave-context/', lvx.employee_leave_context, name='leave_context_api'),
    path('leave/', views.LeaveRequestListView.as_view(), name='leave_list'),
    path('leave/create/', views.LeaveRequestCreateView.as_view(), name='leave_create'),
    path('leave/<int:pk>/', views.LeaveRequestDetailView.as_view(), name='leave_detail'),
    path('leave/<int:pk>/attachment/', views.leave_attachment, name='leave_attachment'),
    path('leave/<int:pk>/edit/', views.LeaveRequestUpdateView.as_view(), name='leave_edit'),
    path('leave/<int:pk>/approve/', views.leave_approve, name='leave_approve'),
    path('leave/<int:pk>/reject/', views.leave_reject, name='leave_reject'),
    path('payroll/', views.PayrollListView.as_view(), name='payroll_list'),
    path('payroll/create/', views.PayrollCreateView.as_view(), name='payroll_create'),
    path('payroll/bulk-process/', vx.payroll_bulk_process_month, name='payroll_bulk_process'),
    path('payroll/bulk-pay/', vx.payroll_bulk_pay_month, name='payroll_bulk_pay'),
    path('payroll/generate-drafts/', vx.payroll_generate_drafts, name='payroll_generate_drafts'),
    path('payroll/api/template/<int:pk>/', vx.payroll_template_json, name='payroll_template_json'),
    path('payroll/templates/', vx.PayrollTemplateListView.as_view(), name='payroll_template_list'),
    path('payroll/templates/create/', vx.PayrollTemplateCreateView.as_view(), name='payroll_template_create'),
    path('payroll/templates/<int:pk>/edit/', vx.PayrollTemplateUpdateView.as_view(), name='payroll_template_edit'),
    path('payroll/templates/<int:pk>/delete/', vx.PayrollTemplateDeleteView.as_view(), name='payroll_template_delete'),
    path('payroll/advances/', vx.EmployeeAdvanceListView.as_view(), name='payroll_advance_list'),
    path('payroll/advances/create/', vx.EmployeeAdvanceCreateView.as_view(), name='payroll_advance_create'),
    path('payroll/advances/<int:pk>/', vx.EmployeeAdvanceDetailView.as_view(), name='payroll_advance_detail'),
    path('payroll/api/deduction-preview/', vx.payroll_deduction_preview, name='payroll_deduction_preview'),
    path('payroll/wps-export/', vx.wps_export, name='wps_export'),
    path('payroll/<int:pk>/', views.PayrollDetailView.as_view(), name='payroll_detail'),
    path('payroll/<int:pk>/payslip-pdf/', vx.payroll_payslip_pdf, name='payroll_payslip_pdf'),
    path('payroll/<int:pk>/edit/', views.PayrollUpdateView.as_view(), name='payroll_edit'),
    path('payroll/<int:pk>/process/', views.payroll_process, name='payroll_process'),
    path('payroll/<int:pk>/pay/', views.payroll_pay, name='payroll_pay'),
    path('attendance/', av.AttendanceRecordListView.as_view(), name='attendance_list'),
    path('attendance/public/', av.PublicAttendancePunchView.as_view(), name='public_attendance'),
    path('attendance/api/public-punch/', av.attendance_public_punch, name='attendance_public_punch'),
    path('attendance/api/self-punch/', av.attendance_self_punch, name='attendance_self_punch'),
    path('attendance/records/', av.EmployeeAttendanceRecordsView.as_view(), name='attendance_records_self'),
    path('attendance/mark/', av.AttendanceMarkView.as_view(), name='attendance_mark'),
    path('attendance/mark/all-present/', av.attendance_mark_all_present, name='attendance_mark_all_present'),
    path('attendance/api/record/', av.attendance_record_lookup, name='attendance_record_lookup'),
    path('attendance/import/', av.attendance_import_csv, name='attendance_import'),
    path('attendance/summary/export/', av.attendance_summary_export_csv, name='attendance_summary_export'),
    path('attendance/summary/generate/', av.attendance_generate_summaries, name='attendance_summary_generate'),
    path('attendance/summary/finalize/<int:pk>/', av.attendance_finalize_summary, name='attendance_summary_finalize'),
    path(
        'attendance/summary/<int:employee_pk>/<int:year>/<int:month>/',
        vx.AttendanceMonthlySummaryView.as_view(),
        name='attendance_summary_detail',
    ),
    path('attendance/summary/', av.AttendanceMonthlySummaryListView.as_view(), name='attendance_summary_month'),
    path('attendance/settings/', av.AttendanceSettingsView.as_view(), name='attendance_settings'),
    path('attendance/holidays/create/', av.HolidayCreateView.as_view(), name='holiday_create'),
    path('attendance/holidays/<int:pk>/edit/', av.HolidayUpdateView.as_view(), name='holiday_edit'),
    path('attendance/holidays/<int:pk>/delete/', av.HolidayDeleteView.as_view(), name='holiday_delete'),
    path('attendance/holidays/', av.HolidayListView.as_view(), name='holiday_list'),
    path('payroll/gosi-export/', vx.gosi_export, name='gosi_export'),
    path('self-service/profile/', vx.SelfServiceProfileView.as_view(), name='self_service_profile'),
    path('self-service/payslips/', vx.SelfServicePayslipsView.as_view(), name='self_service_payslips'),
    path('self-service/leave/', vx.self_service_leave_redirect, name='self_service_leave'),
    path('self-service/attendance/', vx.SelfServiceAttendanceView.as_view(), name='self_service_attendance'),
    path('self-service/documents/', vx.SelfServiceDocumentsView.as_view(), name='self_service_documents'),
]
