# Generated by Django 5.0.6 on 2026-05-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advances', '0001_initial'),
        ('purchase', '0016_purchaserequestattachment_vendor_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitychequeoutward',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_cheques', to='purchase.vendor'),
        ),
        migrations.AlterField(
            model_name='securitychequeoutward',
            name='party_name',
            field=models.CharField(help_text='Auto-filled from vendor; editable for non-vendor parties', max_length=200),
        ),
    ]
