# Generated by Django 5.1.4 on 2026-04-29 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_company_location_compliance_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='ksacompliance',
            name='muqeem_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaecompliance',
            name='iloe_insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uaecompliance',
            name='iloe_insurance_policy_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='uaecompliance',
            name='iloe_insurance_provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uaecompliance',
            name='unified_number_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ksacompliance',
            name='iqama_number',
            field=models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^(\\d{9})?$', 'Iqama number must be exactly 9 digits, or leave blank.')]),
        ),
        migrations.AlterField(
            model_name='uaecompliance',
            name='unified_number',
            field=models.CharField(blank=True, help_text='15-digit UAE UID', max_length=15, validators=[django.core.validators.RegexValidator('^(\\d{15})?$', 'Enter exactly 15 digits (UID), or leave blank.')]),
        ),
    ]
