# Generated by Django 5.1.4 on 2026-04-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_document_expiry_dashboard_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
