# Generated by Django 5.1.4 on 2026-04-29 12:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_employee_employee_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_requests_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='covering_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='covered_leave_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='leave/medical/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='medical_certificate_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='requested_working_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='submitted_publicly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='gender_restricted',
            field=models.CharField(blank=True, choices=[('', 'None'), ('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='location',
            field=models.CharField(choices=[('uae', 'UAE'), ('ksa', 'KSA'), ('both', 'Both')], default='both', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='min_service_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='once_in_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='pay_type',
            field=models.CharField(choices=[('full', 'Full pay'), ('half', 'Half pay'), ('unpaid', 'Unpaid'), ('tiered', 'Tiered')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='probation_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='religion_restricted',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('hr', 'LeaveRequest').objects.filter(status='pending').update(
                status='pending_manager'
            ),
            lambda apps, schema_editor: apps.get_model('hr', 'LeaveRequest').objects.filter(
                status__in=['pending_manager', 'pending_hr']
            ).update(status='pending'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending_manager', 'Pending manager'), ('pending_hr', 'Pending HR'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending_manager', max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_allowed',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('year', models.PositiveIntegerField()),
                ('entitled_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('used_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('pending_days', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('carried_forward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.leavetype')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', 'leave_type__name'],
                'indexes': [models.Index(fields=['employee', 'year'], name='hr_leavebal_employe_38d436_idx')],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
