# Generated by Django 5.1.4 — reference_number must be NULL when unset so UNIQUE allows multiple rows (empty strings collide).

from datetime import date

from django.db import migrations, models


def normalize_leave_references(apps, schema_editor):
    LeaveRequest = apps.get_model('hr', 'LeaveRequest')
    LeaveRequest.objects.filter(reference_number='').update(reference_number=None)
    for lr in LeaveRequest.objects.filter(reference_number__isnull=True).order_by('pk'):
        yr = lr.created_at.year if getattr(lr, 'created_at', None) else date.today().year
        ref = f'LR-{yr}-{lr.pk:04d}'
        LeaveRequest.objects.filter(pk=lr.pk).update(reference_number=ref)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_hr_leave_module_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='reference_number',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.RunPython(normalize_leave_references, noop_reverse),
    ]
