# Generated by Django 5.1.4 on 2026-04-29 13:15

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_leaverequest_split_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='working_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='absent_deduction_days',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_holidays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_late_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_overtime_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_working_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='total_working_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half day'), ('weekend', 'Weekend'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='AttendanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('shift_start', models.TimeField(default=datetime.time(9, 0))),
                ('shift_end', models.TimeField(default=datetime.time(18, 0))),
                ('working_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('late_threshold_minutes', models.PositiveIntegerField(default=15)),
                ('half_day_hours', models.DecimalField(decimal_places=2, default=Decimal('4.50'), max_digits=5)),
                ('overtime_threshold_hours', models.DecimalField(decimal_places=2, default=Decimal('9.00'), max_digits=5)),
                ('late_deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('overtime_rate_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=8)),
                ('auto_mark_absent', models.BooleanField(default=True)),
                ('working_days_in_month', models.PositiveIntegerField(default=22, help_text='Default denominator for per-day salary when calendar working-day count is not used.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance settings',
                'verbose_name_plural': 'Attendance settings',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('location', models.CharField(choices=[('uae', 'UAE'), ('ksa', 'KSA'), ('both', 'Both')], default='both', max_length=10)),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Holiday',
                'ordering': ['date', 'name'],
            },
        ),
    ]
