# Generated by Django 5.0.6 on 2026-04-29 16:03

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def _migrate_payroll_allowances_and_company(apps, schema_editor):
    Payroll = apps.get_model('hr', 'Payroll')
    PayrollAllowanceLine = apps.get_model('hr', 'PayrollAllowanceLine')
    Employee = apps.get_model('hr', 'Employee')

    for p in Payroll.objects.all().iterator():
        updates = {}
        if not p.company_id and p.employee_id:
            ecid = (
                Employee.objects.filter(pk=p.employee_id).values_list('company_id', flat=True).first()
            )
            if ecid:
                updates['company_id'] = ecid
        amt = p.allowances or Decimal('0')
        if amt > 0 and not PayrollAllowanceLine.objects.filter(payroll_id=p.pk).exists():
            PayrollAllowanceLine.objects.create(
                payroll_id=p.pk,
                code='OTHER',
                description='Allowances (migrated)',
                amount=amt,
                is_taxable=False,
                source='manual',
                is_active=True,
            )
        if updates:
            Payroll.objects.filter(pk=p.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_attendance_module_v2'),
        ('settings_app', '0011_company_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Legal entity for reporting/WPS/GOSI filtering; defaults from employee when blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='settings_app.company'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payslip_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='allowances',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total allowances (sum of allowance lines; kept for net salary / journals).', max_digits=15),
        ),
        migrations.CreateModel(
            name='PayrollAllowanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_taxable', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Auto'), ('attendance', 'Attendance')], default='manual', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowance_lines', to='hr.payroll')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payroll_id', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PayrollTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(choices=[('uae', 'UAE'), ('ksa', 'KSA'), ('both', 'Both')], default='both', max_length=10)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('allowance_lines', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_templates', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(_migrate_payroll_allowances_and_company, migrations.RunPython.noop),
    ]
