# Generated by Django 5.0.6 on 2026-04-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0013_payroll_allowances_company_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward_cap',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum days that may carry from prior year (e.g. 15 UAE annual, 30 KSA annual).', null=True),
        ),
    ]
