# Generated by Django 5.0.6 on 2026-04-29 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0014_leave_type_carry_forward_cap'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeebankdetail',
            name='account_number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='employeebankdetail',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
