# Generated by Django 5.0.6 on 2026-04-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0015_employee_bank_detail_name_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='uaecompliance',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='Employee bank IBAN for WPS (overrides HR bank profile if set).', max_length=34),
        ),
        migrations.AddField(
            model_name='uaecompliance',
            name='bank_routing_code',
            field=models.CharField(blank=True, help_text='Employee bank routing code for WPS (overrides HR bank profile if set).', max_length=20),
        ),
    ]
