# Generated by Django 5.0.6 on 2026-04-29 19:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def forwards_gosi_denorm(apps, schema_editor):
    GOSIRecord = apps.get_model('hr', 'GOSIRecord')
    for g in GOSIRecord.objects.select_related('payroll', 'payroll__employee').iterator():
        p = g.payroll
        if not p:
            continue
        g.month = p.month
        g.basic_salary = g.gross_up_basic_for_rates or p.basic_salary or Decimal('0')
        g.employee_id = p.employee_id
        g.company_id = getattr(p, 'company_id', None) or getattr(p.employee, 'company_id', None)
        g.total_contribution = (g.employee_contribution or Decimal('0')) + (g.employer_contribution or Decimal('0'))
        g.save(
            update_fields=[
                'month',
                'basic_salary',
                'employee_id',
                'company_id',
                'total_contribution',
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_employee_advance_repayment'),
        ('settings_app', '0012_company_wps_fields_uae_compliance_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='gosirecord',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gosi_records', to='settings_app.company'),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gosi_records', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='employee_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='employer_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='gosi_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='iqama_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='month',
            field=models.DateField(blank=True, help_text='First day of payroll month', null=True),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='nationality',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gosirecord',
            name='total_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='payrollemployercontribution',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.RunPython(forwards_gosi_denorm, migrations.RunPython.noop),
    ]
