# Generated by Django 5.0.6 on 2026-04-29 19:58

from decimal import Decimal
from django.db import migrations, models


def forwards_cleanup_payroll_templates(apps, schema_editor):
    PayrollTemplate = apps.get_model('hr', 'PayrollTemplate')
    PayrollTemplate.objects.filter(
        name='Salary Payslip',
        company_id__isnull=True,
        basic_salary=Decimal('0'),
    ).delete()

    for t in PayrollTemplate.objects.all():
        changed = False
        b = Decimal(str(t.basic_salary)).quantize(Decimal('0.01'))
        if t.basic_salary != b:
            t.basic_salary = b
            changed = True
        lines = t.allowance_lines or []
        new_lines = []
        for row in lines:
            if not isinstance(row, dict):
                continue
            code = (row.get('code') or '').strip()
            if not code:
                continue
            try:
                amt = Decimal(str(row.get('amount', '0')).replace(',', '')).quantize(Decimal('0.01'))
            except Exception:
                continue
            if amt <= 0:
                continue
            desc = str(row.get('description') or '')[:200]
            new_lines.append({'code': code[:40], 'description': desc, 'amount': str(amt)})
        if new_lines != lines:
            t.allowance_lines = new_lines
            changed = True
        if changed:
            t.save(update_fields=['basic_salary', 'allowance_lines', 'updated_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_gosi_record_expand_and_employer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrolltemplate',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.RunPython(forwards_cleanup_payroll_templates, migrations.RunPython.noop),
    ]
