# Generated by Django 5.x

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0020_payrollsettings_iloe_deduct_and_iloe_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_template',
            field=models.ForeignKey(
                blank=True,
                help_text='Optional salary package; allowances can be pulled into payroll from this template.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees',
                to='hr.payrolltemplate',
            ),
        ),
        migrations.AddField(
            model_name='payroll',
            name='gross_salary',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Basic plus structural allowances (excludes variable overtime); used for leave/daily rate.',
                max_digits=15,
            ),
        ),
    ]
