# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0025_seed_public_holidays_2026_uae_ksa'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(
                choices=[
                    ('manual', 'Manual'),
                    ('import', 'Import'),
                    ('biometric', 'Biometric'),
                    ('public_link', 'Public link'),
                    ('self_service', 'Self-service'),
                ],
                default='manual',
                max_length=20,
            ),
        ),
    ]
