# Generated by Django 5.1.4 on 2026-05-16 08:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0026_attendance_geo_public_self_service'),
        ('projects', '0009_project_technicians_and_attendance_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Optional job / site — use for technician labour on a project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='overtime_rate_holiday',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Worked time on a public holiday (all hours treated as OT with this multiplier).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='overtime_rate_night',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Night OT multiplier (check-out 22:00–04:00, or set manually on the record).', max_digits=8),
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='overtime_rate_normal',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Daytime OT multiplier (UAE payroll). Hourly rate = (basic × 12) / 365 / 8.', max_digits=8),
        ),
    ]
