# Generated by Django 5.1.4 on 2026-05-26 09:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0030_remove_non_uae_leave_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('limited', 'Limited (fixed-term)'), ('unlimited', 'Unlimited')], default='limited', help_text='Used for legacy pre-2022 unlimited-contract resignation rules.', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_uae_national',
            field=models.BooleanField(default=False, help_text='UAE nationals are covered under GPSSA; end-of-service gratuity does not apply.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='termination_type',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('resigned', 'Resigned'), ('terminated', 'Terminated'), ('redundancy', 'Redundancy'), ('contract_end', 'Contract end')], default='', help_text='Set when employment ends; used for EOSG resignation adjustments.', max_length=20),
        ),
        migrations.CreateModel(
            name='GratuitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('snapshot_date', models.DateField()),
                ('years_of_service', models.DecimalField(decimal_places=2, max_digits=8)),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('calculated_gratuity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('adjustment_factor', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=8)),
                ('final_gratuity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratuity_eos_snapshots', to='hr.employee')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratuity snapshot',
                'verbose_name_plural': 'Gratuity snapshots',
                'ordering': ['-snapshot_date', '-pk'],
            },
        ),
    ]
