# Generated by Django 5.1.4 on 2026-07-01 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0040_alter_employee_options_and_more'),
        ('mes', '0007_purge_oracle_import_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='production_order',
            field=models.ForeignKey(blank=True, help_text='Optional MES production order — use for factory labour costing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='mes.productionorder'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='routing_operation',
            field=models.ForeignKey(blank=True, help_text='Optional routing step for operation-level labour.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='mes.routingoperation'),
        ),
    ]
