# Generated by Django 5.1.4 on 2026-07-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_templates_team_pipeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='birthday_email_body',
            field=models.TextField(blank=True, default='Dear {first_name},\n\nHappy Birthday from everyone at {company_name}!\n\nWe hope your special day is filled with joy and celebration.\n\nWarm regards,\n{company_name} HR Team', help_text='Same placeholders as subject. Plain text email body.'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='birthday_email_enabled',
            field=models.BooleanField(default=False, help_text='Send an automated birthday email to employees on their date of birth (daily cron).'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='birthday_email_subject',
            field=models.CharField(blank=True, default='Happy Birthday, {first_name}! — {company_name}', help_text='Placeholders: {first_name}, {last_name}, {full_name}, {employee_code}, {company_name}, {department}, {designation}, {age}', max_length=200),
        ),
        migrations.CreateModel(
            name='EmployeeBirthdayEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_year', models.PositiveIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birthday_email_logs', to='hr.employee')),
            ],
            options={
                'verbose_name': 'Birthday email log',
                'verbose_name_plural': 'Birthday email logs',
                'ordering': ['-sent_at'],
                'unique_together': {('employee', 'calendar_year')},
            },
        ),
    ]
