# Generated by Django 5.1.4 on 2026-07-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0042_payrollsettings_birthday_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='additional_contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_contact_location',
            field=models.CharField(blank=True, help_text='City, address, or region for the additional contact.', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='employee',
            name='additional_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
