# Generated by Django 5.1.4 on 2026-06-30 20:49

from django.db import migrations, models

PRODUCTION_LINE = {
    'CUT': 10,
    'EDGE': 20,
    'CNC': 30,
    'ASSY': 40,
    'UPH': 50,
    'METAL': 60,
    'PAINT': 70,
    'QC': 80,
    'DISP': 90,
}
LOCATIONS = {
    'SAMPLE': 910,
    'STORE': 920,
    'RECYCLE': 930,
}


def set_production_step_flags(apps, schema_editor):
    WorkCenter = apps.get_model('mes', 'WorkCenter')
    for code, seq in PRODUCTION_LINE.items():
        WorkCenter.objects.filter(code=code).update(
            is_production_step=True,
            sequence_order=seq,
        )
    for code, seq in LOCATIONS.items():
        WorkCenter.objects.filter(code=code).update(
            is_production_step=False,
            sequence_order=seq,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0002_tablet_scan_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcenter',
            name='is_production_step',
            field=models.BooleanField(
                default=False,
                help_text='True for line stations in the Scan OUT routing path; false for sample room, storage, etc.',
            ),
        ),
        migrations.RunPython(set_production_step_flags, migrations.RunPython.noop),
    ]
