# Generated by Django 5.1.4 on 2026-06-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0003_workcenter_production_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productionorder',
            options={'ordering': ['-due_date', '-created_at'], 'verbose_name': 'Production order'},
        ),
        migrations.AddField(
            model_name='productionorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('created', 'Created'), ('in_wip', 'In WIP'), ('at_qc', 'At QC'), ('hold', 'Hold'), ('done', 'Done'), ('scrapped', 'Scrapped')], default='pending', max_length=20),
        ),
    ]
