# Generated by Django 5.1.4 on 2026-06-30 21:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0004_po_workflow'),
        ('settings_app', '0036_other_service_expenses_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Material cost per BOM unit (AED) for roll-up.', max_digits=12),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='overhead_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Factory overhead applied to material + labour (percent).', max_digits=5),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='capacity_units_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Nominal throughput capacity (units/hr) for planning.', max_digits=10),
        ),
        migrations.AddField(
            model_name='workcenter',
            name='cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Machine + labour standard rate (AED/hr) for costing.', max_digits=10),
        ),
        migrations.CreateModel(
            name='RoutingOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence_order', models.PositiveSmallIntegerField(default=100)),
                ('standard_minutes', models.PositiveSmallIntegerField(default=15, help_text='Standard run time for this operation (minutes per unit/part).')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_operations', to='mes.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routing_operations', to='mes.workcenter')),
            ],
            options={
                'verbose_name': 'Routing operation',
                'ordering': ['production_order', 'sequence_order', 'id'],
                'unique_together': {('production_order', 'work_center')},
            },
        ),
    ]
