# Generated by Django 5.1.4 on 2026-07-01 04:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def remap_po_statuses(apps, schema_editor):
    ProductionOrder = apps.get_model('mes', 'ProductionOrder')
    ProductionOrder.objects.filter(status='in_progress').update(status='in_production')
    ProductionOrder.objects.filter(status='done').update(status='finished')


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0041_templates_team_pipeline'),
        ('inventory', '0028_item_warehouse_storage'),
        ('mes', '0007_purge_oracle_import_orders'),
        ('settings_app', '0036_other_service_expenses_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bomitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_bom_lines', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='Overall crew assigned to this production order.', related_name='mes_production_orders', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='cost_frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='final_total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Frozen total cost when order is finished.', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='source_template_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='routingoperation',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to this operation.', related_name='mes_routing_operations', to='hr.employee'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='overhead_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Factory overhead applied to material + labour + machine (percent).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('released', 'Released'), ('in_production', 'In Production'), ('finished', 'Finished'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='routingoperation',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=100, help_text='Operation order; lower numbers run first.'),
        ),
        migrations.CreateModel(
            name='ProductionOrderStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_po_status_changes', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='mes.productionorder')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product template',
                'ordering': ['company', 'name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product_template',
            field=models.ForeignKey(blank=True, help_text='Source template (snapshot only — template edits do not affect this PO).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='mes.producttemplate'),
        ),
        migrations.CreateModel(
            name='TemplateBOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('part_name', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('panel', 'Panel'), ('veneer', 'Veneer'), ('hardware', 'Hardware'), ('edge_tape', 'Edge tape'), ('finish', 'Finish')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('item_code', models.CharField(blank=True, max_length=80)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mes_template_bom_lines', to='inventory.item')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mes.templatebomitem')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='mes.producttemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template BOM item',
                'ordering': ['template', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateRoutingOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.PositiveSmallIntegerField(default=100)),
                ('std_time_minutes', models.PositiveSmallIntegerField(default=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_ops', to='mes.producttemplate')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_routing_ops', to='mes.workcenter')),
            ],
            options={
                'verbose_name': 'Template routing operation',
                'ordering': ['template', 'sequence', 'id'],
                'unique_together': {('template', 'work_center')},
            },
        ),
        migrations.RunPython(remap_po_statuses, migrations.RunPython.noop),
    ]
