# Generated by Django 5.1.4 on 2026-07-09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mes', '0011_actual_count'),
        ('settings_app', '0038_vendor_bill_approval_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actualcountsetting',
            name='presence_state',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Per-item in-frame flag — prevents re-counting the same visible object on every scan.',
            ),
        ),
        migrations.AlterField(
            model_name='actualcountsetting',
            name='capture_interval_seconds',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Seconds between automatic camera captures (0 = scan again as soon as the previous finishes).',
            ),
        ),
        migrations.CreateModel(
            name='ActualCountExampleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item_name', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='mes/actual_examples/%Y/%m/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='settings_app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actual count example image',
                'ordering': ['item_name', 'id'],
                'indexes': [models.Index(fields=['company', 'item_name'], name='mes_actualco_company_8a1f2d_idx')],
            },
        ),
    ]
