# Generated by Django 6.0.1 on 2026-03-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_customer_credit_limit_customer_payment_terms'),
        ('projects', '0003_project_billing_type_project_contract_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='job_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_for_customers', to='projects.project', verbose_name='Project'),
        ),
        migrations.AddField(
            model_name='customer',
            name='scope',
            field=models.JSONField(blank=True, default=list, help_text='Disciplines: FF, FA, EM, FLS, MEP'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
