# Generated by Django 6.0.1 on 2026-03-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_vat_website_scope_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='trn',
            field=models.CharField(blank=True, help_text='Tax registration / VAT number for B2B invoices', max_length=20, verbose_name='VAT (TRN)'),
        ),
    ]
