# Generated by Django 5.0.6 on 2026-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customer_b2b_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='trn_document',
            field=models.FileField(blank=True, help_text='Optional. VAT/TRN certificate (PDF or image) for B2B.', max_length=500, upload_to='crm/customer_documents/%Y/%m/', verbose_name='TRN document'),
        ),
    ]
