# Generated by Django 5.1.4 on 2026-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_crm_lead_kanban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='job_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('amc', 'AMC'), ('project', 'Project'), ('direct_sale', 'Direct Sale'), ('maintenance', 'Maintenance')], default='', max_length=20, verbose_name='Job type'),
        ),
    ]
