# Generated by Django 5.1.4 on 2026-05-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_assigned_to_salesperson(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    Employee = apps.get_model('hr', 'Employee')

    for customer in Customer.objects.exclude(assigned_to_id__isnull=True).iterator():
        emp = Employee.objects.filter(user_id=customer.assigned_to_id).first()
        if emp:
            customer.assigned_salesperson_id = emp.pk
            customer.save(update_fields=['assigned_salesperson_id'])


def migrate_salesperson_to_assigned_to(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    Employee = apps.get_model('hr', 'Employee')

    for customer in Customer.objects.exclude(assigned_salesperson_id__isnull=True).iterator():
        emp = Employee.objects.filter(pk=customer.assigned_salesperson_id).first()
        if emp and emp.user_id:
            customer.assigned_to_id = emp.user_id
            customer.save(update_fields=['assigned_to_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_customer_assigned_to_salesman'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='assigned_salesperson',
            field=models.ForeignKey(
                blank=True,
                help_text='Sales employee responsible for this lead (from HR → Employees).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_crm_leads',
                to='hr.employee',
                verbose_name='Assigned salesman',
            ),
        ),
        migrations.RunPython(migrate_assigned_to_salesperson, migrate_salesperson_to_assigned_to),
        migrations.RemoveField(
            model_name='customer',
            name='assigned_to',
        ),
    ]
