# Generated by Django 5.1.4 on 2026-05-28 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customer_assigned_salesperson'),
        ('hr', '0031_uae_eosg_gratuity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='assigned_salesperson',
            field=models.ForeignKey(blank=True, help_text='Sales employee responsible for this lead or customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crm_leads', to='hr.employee', verbose_name='Assigned salesman'),
        ),
    ]
