# Generated by Django 5.0.6 on 2026-06-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_task_customer_optional_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
