# Generated by Django 5.1.4 on 2026-07-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_crmleadkanbanstage_is_site_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_source',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '—'),
                    ('facebook', 'Facebook'),
                    ('instagram', 'Instagram'),
                    ('tiktok', 'TikTok'),
                    ('google', 'Google'),
                    ('seo', 'SEO'),
                    ('reference', 'Reference'),
                    ('direct_enquiry', 'Direct Enquiry'),
                    ('linkedin', 'LinkedIn'),
                    ('outdoor_sales', 'Outdoor Sales'),
                    ('tele_calling', 'Tele Calling'),
                ],
                default='',
                help_text='Where this lead came from (Facebook, Google, referral, etc.).',
                max_length=30,
                verbose_name='Source',
            ),
        ),
    ]
