# Generated by Django 5.1.4 on 2026-07-02

from django.db import migrations, models


def map_legacy_sources(apps, schema_editor):
    Customer = apps.get_model('crm', 'Customer')
    mapping = {
        'instagram': 'other',
        'tiktok': 'other',
        'seo': 'other',
        'direct_enquiry': 'other',
        'linkedin': 'other',
        'outdoor_sales': 'sales',
        'tele_calling': 'sales',
    }
    for old, new in mapping.items():
        Customer.objects.filter(source_of_lead=old).update(source_of_lead=new)


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_customer_lead_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lead_source',
            new_name='source_of_lead',
        ),
        migrations.AlterField(
            model_name='customer',
            name='source_of_lead',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '—'),
                    ('facebook', 'Facebook'),
                    ('whatsapp', 'WhatsApp'),
                    ('google', 'Google'),
                    ('sales', 'Sales'),
                    ('reference', 'Reference'),
                    ('other', 'Other'),
                ],
                default='',
                help_text='Where this lead came from (Facebook, WhatsApp, Google, etc.).',
                max_length=30,
                verbose_name='Source of lead',
            ),
        ),
        migrations.RunPython(map_legacy_sources, migrations.RunPython.noop),
    ]
