# Generated by Django 5.1.4 on 2026-07-02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_source_of_lead_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visit_date', models.DateField(db_column='date')),
                ('location', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.CharField(
                    choices=[
                        ('interested', 'Interested'),
                        ('not_interested', 'Not Interested'),
                        ('follow_up', 'Follow-up Needed'),
                        ('converted', 'Converted'),
                        ('other', 'Other'),
                    ],
                    default='follow_up',
                    max_length=30,
                )),
                ('created_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL,
                )),
                ('updated_by', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL,
                )),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_visits', to='crm.customer')),
                ('salesman', models.ForeignKey(
                    blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name='crm_site_visits', to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Site visit log',
                'verbose_name_plural': 'Site visit logs',
                'ordering': ['-visit_date', '-created_at'],
            },
        ),
    ]
