# Generated by Django 5.1.4 on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_sitevisitlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitevisitlog',
            name='visit_datetime',
            field=models.DateTimeField(
                blank=True,
                help_text='Exact visit timestamp (public form or manual log).',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='sitevisitlog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitlog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sitevisitlog',
            name='selfie',
            field=models.ImageField(blank=True, max_length=500, upload_to='crm_site_visits/%Y/%m/'),
        ),
    ]
