# Generated by Django 6.0.1 on 2026-03-26 06:52

from django.db import migrations, models
from django.utils import timezone


def backfill_status_from_dates(apps, schema_editor):
    Contract = apps.get_model('contracts', 'Contract')
    today = timezone.now().date()
    for c in Contract.objects.all().only('pk', 'start_date', 'end_date', 'status'):
        if c.end_date < today:
            new_status = 'expired'
        elif c.start_date > today:
            new_status = 'upcoming'
        else:
            new_status = 'active'
        if c.status != new_status:
            Contract.objects.filter(pk=c.pk).update(status=new_status)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_contract_is_active_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', help_text='Lifecycle status (editable; can align with dates)', max_length=20),
        ),
        migrations.RunPython(backfill_status_from_dates, noop_reverse),
    ]
