# Generated by Django 6.0.1 on 2026-03-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='terms_and_conditions',
            field=models.TextField(blank=True, help_text='Printed on the contract PDF; defaults from Company Settings and can be edited per contract.'),
        ),
    ]
