# Generated by Django 5.1.4 on 2026-06-29 05:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_contract_terms_and_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDocumentExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('document_name', models.CharField(max_length=200)),
                ('expiry_date', models.DateField()),
                ('remind_before_days', models.PositiveIntegerField(default=10, help_text='Reminder this many days before expiry date')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_expiries', to='contracts.contract')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document expiry',
                'verbose_name_plural': 'Document expiries',
                'ordering': ['expiry_date', 'document_name'],
            },
        ),
    ]
